config/routes.rb
SFAppSpANDFac::Application.routes.draw do
  devise_for :users

  resources :faculties
  resources :specialties
  resources :recruitmentoffices
  resources :ranks
  resources :consists
  resources :positions
  resources :personalfiles do
    get "more", on: :collection
    
    collection do
      delete 'destroy_multiple'
    end 
  end

  root to: "personalfiles#index"
  

end

app/models/consist.rb
class Consist < ActiveRecord::Base
	has_many :personalfiles
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
	has_many :specialties
end

app/models/personalfile.rb
class Personalfile < ActiveRecord::Base
	
	belongs_to :rank
	belongs_to :specialty
	belongs_to :consist
	belongs_to :recruitmentoffice
	belongs_to :position

	validates :firstname, presence: true
	validates :middlename, presence: true
	validates :lastname, presence: true
end

app/models/position.rb
class Position < ActiveRecord::Base
	has_many :personalfiles
end

app/models/rank.rb
class Rank < ActiveRecord::Base
	has_many :personalfiles
end

app/models/recruitmentoffice.rb
class Recruitmentoffice < ActiveRecord::Base
	has_many :personalfiles
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
	belongs_to :faculty
	has_many :personalfiles
end
            

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/consists_controller.rb
class ConsistsController < ApplicationController

	before_filter :find_consist, only: [:show, :edit, :update, :destroy]

	def new
		@con = Consist.new
	end

	def create
		@con = Consist.new consist_params
		@con.save
		redirect_to new_consist_path
	end
	
	def show
	end

	def index
		@consists = Consist.all
	end

	def edit
	end
	
	def update
		@con.update_attributes(consist_params)
		redirect_to consists_path
	end

	def destroy
		@con.destroy
		redirect_to consists_path
	end
		
	private 

	def find_consist
		@con = Consist.find(params[:id])
	end

	def consist_params
		params[:consist].permit(:name)
	end
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController

	before_filter :find_faculty, only: [:show, :edit, :update, :destroy]

	def new
		@fac = Faculty.new
	end

	def create
		@fac = Faculty.new faculty_params
		@fac.save
		redirect_to new_faculty_path
	end
	
	def show
	end

	def index
		@faculties = Faculty.all
	end

	def edit
	end
	
	def update
		@fac.update_attributes(faculty_params)
		redirect_to faculties_path
	end

	def destroy
		@fac.destroy
		redirect_to faculties_path
	end
		
	private 

	def find_faculty
		@fac = Faculty.find(params[:id])
	end

	def faculty_params
		params[:faculty].permit(:facultyname)
	end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
	def new
		@pos = Position.new
	end

	def create
		@pos = Position.new position_params
		@pos.save
		redirect_to new_position_path
	end
	def show
		@pos = Position.find(params[:id])
	end
	def index
		@positions = Position.all
	end

	def edit
		@pos = Position.find(params[:id])
	end
	
	def update
		@pos = Position.find(params[:id])
		@pos.update_attributes(position_params)
		redirect_to positions_path
	end

	def destroy
		@pos = Position.find(params[:id])
		@pos.destroy
		redirect_to positions_path
	end
		
	private 

	def position_params
		params[:position].permit(:name)
	end
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
	def new
		@ran = Rank.new
	end

	def create
		@ran = Rank.new rank_params
		@ran.save
		redirect_to new_rank_path
	end
	def show
		@ran = Rank.find(params[:id])
	end
	def index
		@ranks = Rank.all
	end

	def edit
		@ran = Rank.find(params[:id])
	end
	
	def update
		@ran = Rank.find(params[:id])
		@ran.update_attributes(rank_params)
		redirect_to ranks_path
	end

	def destroy
		@ran = Rank.find(params[:id])
		@ran.destroy
		redirect_to ranks_path
	end
		
	private 

	def rank_params
		params[:rank].permit(:name)
	end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
	def show
		@per = Personalfile.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consists_helper.rb
module ConsistsHelper
end

app/helpers/facultis_helper.rb
module FacultisHelper
end

app/helpers/personalfiles_helper.rb
module PersonalfilesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/recruitmentoffices_helper.rb
module RecruitmentofficesHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/helpers/specialties_helper.rb
module SpecialtiesHelper
end

app/views/consists/_form.html.erb
<%= link_to "Весь состав", consists_path, :class => "btn" %>
<%= form_for @con do |f| -%>
	Название состава:<br />
	<%= f.text_field :name %><br />
	<%= f.submit "Сохранить", :class => "btn btn-success" %>
<% end -%>
<hr>

app/views/consists/edit.html.erb
<%= render 'form' %>

app/views/consists/index.html.erb
<%= link_to "Добавить состав", new_consist_path, :class => "btn" %>
<hr>
<table class="table table-striped table-bordered">
	<% if !@consists.blank? %>
	<% @consists.each do |consist| %>
	    <tr>
	    	<td>
	    		<%= consist.name %>
	    	</td>	
	  		<td>
	  			<%= link_to 'Изменить', edit_consist_path(consist), :class => 'btn btn-mini' %>
	  		</td>
	  		<td>
	  			<%= link_to 'Удалить', consist, method: :delete, :class => 'btn btn-mini btn-danger' %>
	  		</td>
	    </tr>
	<% end %>
	<% else %>
	  
	<% end %>
</table>
<hr>
<div>
<% if !@consists.blank? %>

<%= select_tag :consist, options_for_select(@consists.map{ |f| [f.name, f.name] }) %>

<% else %>

<% end %>
</div>

app/views/positions/_form.html.erb
<%= link_to "Все должности", positions_path, :class => "btn" %>
<%= form_for @pos do |f| -%>
	Название должности:<br />
	<%= f.text_field :name %><br />
	<%= f.submit "Сохранить", :class => "btn btn-success" %>
<% end -%>
<hr>

app/views/positions/edit.html.erb
<%= render 'form' %>

app/views/positions/index.html.erb
<%= link_to "Добавить должность", new_position_path, :class => "btn" %>
<hr>
<table class="table table-striped table-bordered">
	<% if !@positions.blank? %>
	<% @positions.each do |position| %>
	    <tr>
	    	<td>
	    		<%= position.name %>
	    	</td>
	    	<td>
	  			<%= link_to 'Изменить', edit_position_path(position), :class => 'btn btn-mini' %>
	  		</td>	
	  		<td>
	  			<%= link_to 'Удалить', position, method: :delete, :class => 'btn btn-mini btn-danger' %>
	  		</td>
	    </tr>
	<% end %>
	<% else %>
	  
	<% end %>
</table>
<hr>
<div>
<% if !@positions.blank? %>

<%= select_tag :position, options_for_select(@positions.map{ |f| [f.name, f.name] }) %>

<% else %>

<% end %>
</div>

app/views/ranks/_form.html.erb
<%= link_to "Все звания", ranks_path, :class => "btn" %>
<%= form_for @ran do |f| -%>
	Название звания:<br />
	<%= f.text_field :name %><br />
	<%= f.submit "Сохранить", :class => "btn btn-success"%>
<% end -%>
<hr>

app/views/ranks/edit.html.erb
<%= render 'form' %>

app/views/ranks/index.html.erb
<%= link_to "Добавить звание", new_rank_path, :class => "btn" %>
<hr>
<div class = "123">
<table class="table table-striped table-bordered">
	<% if !@ranks.blank? %>
	<% @ranks.each do |rank| %>
	    <tr>
	    	<td>
	    		<%= rank.name %>
	    	</td>
	    	<td>
	  			<%= link_to 'Изменить', edit_rank_path(rank), :class => 'btn btn-mini' %>
	  		</td>	
	  		<td>
	  			<%= link_to 'Удалить', rank, method: :delete, :class => 'btn btn-mini btn-danger' %>
	  		</td>
	    </tr>
	<% end %>
	<% else %>
	  
	<% end %>
</table>
</div>
<hr>
<div>
<% if !@ranks.blank? %>

<%= select_tag :rank, options_for_select(@ranks.map{ |f| [f.name, f.name] }) %>

<% else %>

<% end %>
</div>