config/routes.rb
SFAppSpANDFac::Application.routes.draw do
  devise_for :users

  resources :faculties
  resources :specialties
  resources :recruitmentoffices
  resources :ranks
  resources :consists
  resources :positions
  resources :personalfiles do
    get "more", on: :collection
    
    collection do
      delete 'destroy_multiple'
    end 
  end

  root to: "personalfiles#index"
  

end

app/models/consist.rb
class Consist < ActiveRecord::Base
	has_many :personalfiles
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
	has_many :specialties
end

app/models/personalfile.rb
class Personalfile < ActiveRecord::Base
	
	belongs_to :rank
	belongs_to :specialty
	belongs_to :consist
	belongs_to :recruitmentoffice
	belongs_to :position

	validates :firstname, presence: true
	validates :middlename, presence: true
	validates :lastname, presence: true
end

app/models/position.rb
class Position < ActiveRecord::Base
	has_many :personalfiles
end

app/models/rank.rb
class Rank < ActiveRecord::Base
	has_many :personalfiles
end

app/models/recruitmentoffice.rb
class Recruitmentoffice < ActiveRecord::Base
	has_many :personalfiles
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
	belongs_to :faculty
	has_many :personalfiles
end
            

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/consists_controller.rb
class ConsistsController < ApplicationController

	before_filter :find_consist, only: [:show, :edit, :update, :destroy]

	def new
		@con = Consist.new
	end

	def create
		@con = Consist.new consist_params
		@con.save
		redirect_to new_consist_path
	end
	
	def show
	end

	def index
		@consists = Consist.all
	end

	def edit
	end
	
	def update
		@con.update_attributes(consist_params)
		redirect_to consists_path
	end

	def destroy
		@con.destroy
		redirect_to consists_path
	end
		
	private 

	def find_consist
		@con = Consist.find(params[:id])
	end

	def consist_params
		params[:consist].permit(:name)
	end
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController

	before_filter :find_faculty, only: [:show, :edit, :update, :destroy]

	def new
		@fac = Faculty.new
	end

	def create
		@fac = Faculty.new faculty_params
		@fac.save
		redirect_to new_faculty_path
	end
	
	def show
	end

	def index
		@faculties = Faculty.all
	end

	def edit
	end
	
	def update
		@fac.update_attributes(faculty_params)
		redirect_to faculties_path
	end

	def destroy
		@fac.destroy
		redirect_to faculties_path
	end
		
	private 

	def find_faculty
		@fac = Faculty.find(params[:id])
	end

	def faculty_params
		params[:faculty].permit(:facultyname)
	end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
	def new
		@pos = Position.new
	end

	def create
		@pos = Position.new position_params
		@pos.save
		redirect_to new_position_path
	end
	def show
		@pos = Position.find(params[:id])
	end
	def index
		@positions = Position.all
	end

	def edit
		@pos = Position.find(params[:id])
	end
	
	def update
		@pos = Position.find(params[:id])
		@pos.update_attributes(position_params)
		redirect_to positions_path
	end

	def destroy
		@pos = Position.find(params[:id])
		@pos.destroy
		redirect_to positions_path
	end
		
	private 

	def position_params
		params[:position].permit(:name)
	end
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
	def new
		@ran = Rank.new
	end

	def create
		@ran = Rank.new rank_params
		@ran.save
		redirect_to new_rank_path
	end
	def show
		@ran = Rank.find(params[:id])
	end
	def index
		@ranks = Rank.all
	end

	def edit
		@ran = Rank.find(params[:id])
	end
	
	def update
		@ran = Rank.find(params[:id])
		@ran.update_attributes(rank_params)
		redirect_to ranks_path
	end

	def destroy
		@ran = Rank.find(params[:id])
		@ran.destroy
		redirect_to ranks_path
	end
		
	private 

	def rank_params
		params[:rank].permit(:name)
	end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
	def show
		@per = Personalfile.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consists_helper.rb
module ConsistsHelper
end

app/helpers/facultis_helper.rb
module FacultisHelper
end

app/helpers/personalfiles_helper.rb
module PersonalfilesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/recruitmentoffices_helper.rb
module RecruitmentofficesHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/helpers/specialties_helper.rb
module SpecialtiesHelper
end

app/views/faculties/_form.html.erb
<%= link_to "Все факультеты", faculties_path, :class => "btn" %>
<%= form_for @fac do |f| -%>
	Название факультета:<br />
	<%= f.text_field :facultyname %><br />
	<%= f.submit "Сохранить", :class => "btn btn-success" %>
<% end -%>
<hr>

app/views/faculties/edit.html.erb
<%= link_to "Show all", faculties_path %>
<%= form_for @fac do |f| -%>
	Enter your faculty <%= f.text_field :facultyname %><br />
	<%= f.submit "Save" %>
<% end -%>
<hr>

app/views/faculties/index.html.erb
<%= link_to "Добавить факультет", new_faculty_path, :class => "btn" %>
<hr>
<table id="faculties" class="table table-striped table-bordered">
	<% if !@faculties.blank? %>
	<% @faculties.each do |faculty| %>
	    <tr>
	  		<td>
	  			<%= link_to faculty.facultyname, faculty_path(faculty) %>
	  		</td>
	  		<td>
	  			<%= link_to 'Изменить', edit_faculty_path(faculty), :class => 'btn btn-mini' %>
	  		</td>
	  		<td>
	  			<%= link_to 'Удалить', faculty, method: :delete, :class => 'btn btn-mini btn-danger' %>
	  		</td>
	    </tr>
	<% end %>
	<% else %>
	  
	<% end %>
</table>
<hr>
<!--<div id="faculties">
<% if !@faculties.blank? %>

<%= select_tag :faculty, options_for_select(@faculties.map{ |f| [f.facultyname, f.facultyname] }) %>

<% else %>

<% end %>
</div>-->

app/views/faculties/show.html.erb
<%= link_to "Все факультеты", faculties_path, :class => "btn" %>
Go to <%= link_to "Все спицеальности", specialties_path, :class => "btn" %><br/>
Факультет: <%= @fac.facultyname %><br/>
<% if not @fac.specialties.blank? %>
<ul>Специальности: 
	<% @fac.specialties.each do |spec| %>
	<li><%= spec.specialtyname %></li>
<% end %>
</ul>
<% end %>

app/views/references/show.html.erb
<% if !@personalfiles.blank? %>
<% @personalfiles.each do |personalfile| %>

<div class = 'container' id="print-content" >
		<div class = 'top'>
			<div class = 'left'>
				<table>
					<tr><th>Минестерство образования и науки</th></tr>
					<tr><th>Российской федирации</th></tr>
					<tr><td>Федеральное государственное бюджетное</td></tr>
					<tr><td>образовательное учереждение высшего</td></tr>
					<tr><td>профессионального оброзования</td></tr>
					<tr><th>"Тверской государственный университет"</th></tr>
					<tr><th>(ТвГУ)</th></tr>
					<tr><td>Желябова ул., д.33 Тверь. 170100</td></tr>
					<tr><td>Телефоны 34-24-52, 63-02-34</td></tr>
					<tr><td>___________№____________</td></tr>
				</table>
			</div>
			<div class = 'right' , float = 'left'>
				<table>
					<tr><td>Приложение №2</td></tr>
					<tr><td>к Перечню(п..3)</td></tr>
					<tr><td>к Приложению №32</td></tr>
					<tr><td>к Инструкции</td></tr>
					<tr><td>утв. приказом Минобороны РФ</td></tr>
					<tr><td>от 2 октября 2007 г. №400</td></tr>
				</table>

			</div> 
		</div>
		<div class = 'content'>
			<h1 align = 'center' >Справка</h1>
			<p align = 'center'> 
				Выдана гражданину <%= personalfile.firstname %> <%= personalfile.middelname %> <%= personalfile.lastname %> <br>
				<%= personalfile.year %> года рождения, в том что он в _____________поступил имея <br>
				образование __________________ в Тверской государственный университет,<br>
				приказ № _________________ от __________________г. и в настоящее время<br>
				обучаеться на <%= personalfile.academicyear %> курсе по очной форме обучения по напровлению<br>
				подготовки(специальности) ____________________________________________<br>
				______________________________________________________________________<br>
				имеющие государственную акредитацию серия 90А01 № 0000430, гестрицион-<br>
				ный № 0426 от 15.03.2013 года (срок действия до 29.12.2018) и лецензию<br>
				напрово ведения образовательной деятельности серия ААА № 002243, регистра-<br>
				ционный № 0426 от 15.03.2013 года (срок дйствия-бессроно). Свидетельство об<br>
				аккредитации и лицензия выданы Федеральной службой по надзору в сфере обра-<br>
				зования и науки.<br>
			</p>
			<p align = 'center'>
				Окончание обучения в образовательном учереждении (окончание обучения<br>
				по программам послевузовского образования и защиты квалификационной работы)<br>
				<br>
				"_____" ________________  20___ г.<br>
				<br>
				Справка дана для предъявления в отдел военного комиссариата<br>
				___________________________________________________________<br>
				
				Ректор ______________________ А.В.Белоцерковский<br>
				Заключил контракт и приступил к обучеию по программе подготовки<br>
				офицера запаса с 20__г. Оканчание обучения "___" ____________  20__ г.<br>
				Аттестационный материал оформляет _________________________________<br>
				М.П. Начальник (заместитль начальника) военной кафедры<br>
				      (учебного военного центра)______________________________<br>
			</p>
		</div>
	</div>
	<button><a onClick="javascript:CallPrint('print-content');" title="Распечатать проект">Распечатать</a></button>
	<% end %>
	<% else %>
	  
	<% end %>