config/routes.rb
SFAppSpANDFac::Application.routes.draw do
  devise_for :users

  resources :faculties
  resources :specialties
  resources :recruitmentoffices
  resources :ranks
  resources :consists
  resources :positions
  resources :personalfiles do
    get "more", on: :collection
    
    collection do
      delete 'destroy_multiple'
    end 
  end

  root to: "personalfiles#index"
  

end

app/models/consist.rb
class Consist < ActiveRecord::Base
	has_many :personalfiles
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
	has_many :specialties
end

app/models/personalfile.rb
class Personalfile < ActiveRecord::Base
	
	belongs_to :rank
	belongs_to :specialty
	belongs_to :consist
	belongs_to :recruitmentoffice
	belongs_to :position

	validates :firstname, presence: true
	validates :middlename, presence: true
	validates :lastname, presence: true
end

app/models/position.rb
class Position < ActiveRecord::Base
	has_many :personalfiles
end

app/models/rank.rb
class Rank < ActiveRecord::Base
	has_many :personalfiles
end

app/models/recruitmentoffice.rb
class Recruitmentoffice < ActiveRecord::Base
	has_many :personalfiles
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
	belongs_to :faculty
	has_many :personalfiles
end
            

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/consists_controller.rb
class ConsistsController < ApplicationController

	before_filter :find_consist, only: [:show, :edit, :update, :destroy]

	def new
		@con = Consist.new
	end

	def create
		@con = Consist.new consist_params
		@con.save
		redirect_to new_consist_path
	end
	
	def show
	end

	def index
		@consists = Consist.all
	end

	def edit
	end
	
	def update
		@con.update_attributes(consist_params)
		redirect_to consists_path
	end

	def destroy
		@con.destroy
		redirect_to consists_path
	end
		
	private 

	def find_consist
		@con = Consist.find(params[:id])
	end

	def consist_params
		params[:consist].permit(:name)
	end
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController

	before_filter :find_faculty, only: [:show, :edit, :update, :destroy]

	def new
		@fac = Faculty.new
	end

	def create
		@fac = Faculty.new faculty_params
		@fac.save
		redirect_to new_faculty_path
	end
	
	def show
	end

	def index
		@faculties = Faculty.all
	end

	def edit
	end
	
	def update
		@fac.update_attributes(faculty_params)
		redirect_to faculties_path
	end

	def destroy
		@fac.destroy
		redirect_to faculties_path
	end
		
	private 

	def find_faculty
		@fac = Faculty.find(params[:id])
	end

	def faculty_params
		params[:faculty].permit(:facultyname)
	end
end

app/controllers/personalfiles_controller.rb
class PersonalfilesController < ApplicationController

before_action :authenticate_user!
before_filter :find_personalfile, only: [:show, :edit, :update, :destroy]
before_filter :search_personalfile, only: [:index, :more]

	def new
		@per = Personalfile.new
		@ranks = Rank.all
		@faculties = Faculty.all
		@specialties = Specialty.all
		@recruitmentoffices = Recruitmentoffice.all
		@consists = Consist.all
		@positions = Position.all
	end
	def create
		@per = Personalfile.new personalfile_params
		if @per.save
			flash[:success]="Поздравляю! Форма успешно заполнена!" 
		else
			flash[:error]="Ошибка! Заполните пустые поля!" 
		end
		redirect_to new_personalfile_path
	end

	def show
	end
	
	def index
	end

	def more
	end

	def edit
		@ranks = Rank.all
		@faculties = Faculty.all
		@specialties = Specialty.all
		@recruitmentoffices = Recruitmentoffice.all
		@consists = Consist.all
		@positions = Position.all
	end
	
	def update
		@per.update_attributes(personalfile_params)
		redirect_to personalfiles_path
	end

	def destroy
		@per.destroy
		redirect_to personalfiles_path
	end

	def destroy_multiple
		Personalfile.destroy(params[:personalfiles])
		redirect_to more_personalfiles_path
	end
		
	private

	def find_personalfile
		@per = Personalfile.find(params[:id])
	end

	def search_personalfile
		@search = Personalfile.search(params[:q])
    	@personalfiles = @search.result
	end

	def personalfile_params
		params[:personalfile].permit(:firstname, :middlename, :lastname, :gender, :year, :traningcourse, :academicyear, :traning_period, :specialaccount, :mobileorder, :category, :rank_id, :specialty_id, :recruitmentoffice_id, :consist_id, :position_id, :note, :date_of_birth, :place_of_birth, :education, :family_status, :family, :image_url)
	end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
	def new
		@pos = Position.new
	end

	def create
		@pos = Position.new position_params
		@pos.save
		redirect_to new_position_path
	end
	def show
		@pos = Position.find(params[:id])
	end
	def index
		@positions = Position.all
	end

	def edit
		@pos = Position.find(params[:id])
	end
	
	def update
		@pos = Position.find(params[:id])
		@pos.update_attributes(position_params)
		redirect_to positions_path
	end

	def destroy
		@pos = Position.find(params[:id])
		@pos.destroy
		redirect_to positions_path
	end
		
	private 

	def position_params
		params[:position].permit(:name)
	end
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
	def new
		@ran = Rank.new
	end

	def create
		@ran = Rank.new rank_params
		@ran.save
		redirect_to new_rank_path
	end
	def show
		@ran = Rank.find(params[:id])
	end
	def index
		@ranks = Rank.all
	end

	def edit
		@ran = Rank.find(params[:id])
	end
	
	def update
		@ran = Rank.find(params[:id])
		@ran.update_attributes(rank_params)
		redirect_to ranks_path
	end

	def destroy
		@ran = Rank.find(params[:id])
		@ran.destroy
		redirect_to ranks_path
	end
		
	private 

	def rank_params
		params[:rank].permit(:name)
	end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
	def show
		@per = Personalfile.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consists_helper.rb
module ConsistsHelper
end

app/helpers/facultis_helper.rb
module FacultisHelper
end

app/helpers/personalfiles_helper.rb
module PersonalfilesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/recruitmentoffices_helper.rb
module RecruitmentofficesHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/helpers/specialties_helper.rb
module SpecialtiesHelper
end

app/views/personalfiles/_form.html.erb
<%= link_to "Показать таблицу", personalfiles_path, :class => "btn" %>
<hr>
<% if flash[:error] %>
    <div class="alert alert-error"><%= flash[:error] %></div>
<% end %>
<% if flash[:success] %>
    <div class="alert alert-success"><%= flash[:success] %></div>
<% end %>
<%= simple_form_for @per do |f| -%>
	
	<p>
		<%= f.input :firstname, :label => 'Фамилия:' %><br /> 
		<%= f.input :middlename, :label => 'Имя:' %><br />
		<%= f.input :lastname, :label => 'Отчество:'%><br />
	</p>
	<p>
		<%= f.input :image_url %><br>
	</p>
	<p>
		<%= f.input :date_of_birth, as: :date, start_year: Date.today.year - 60, end_year: Date.today.year - 14, order: [:day, :month, :year], :label => 'Дата рождения:' %><br />
	</p>
	<p>
		<%= f.input :gender, as: :radio_buttons, collection: [ "М", "Ж" ], :label => 'Пол:' %>
		 <!--<%= f.select :gender, [["М", "М"], ["Ж", "Ж"]] %>-->
	</p>
	<P>
		<%= f.input :place_of_birth, :label => 'Место рождения:' %>
	</P>
	<p>
		<%= f.input :education, :label => 'Образование:' %>
	</p>
	<p>
		Cемейное положение:<br>
		<%= f.select :family_status, [["холост", "холост"], ["женат", "женат"], ["замужем", "замужем"]], :label => 'Семейное положение:' %>
	</p>
	<p>
		<%= f.input :family, :label => 'Состав семьи:'%>
	</p>
	<p>
		Специальность:<br />
		 <%= f.select :specialty_id, options_for_select(@specialties.map{ |f| [f.specialtyname, f.id] }) %>
	</p>
	<p>
		Курс:<br />
		 <%= f.select :traningcourse, [["1", "1"], ["2", "2"],["3", "3"], ["4", "4"],["5", "5"],["Маг1", "Маг1"],["Маг2", "Маг2"], ["Асп", "Асп"]] %>
	</p>
	<p>
		Учебный год:<br />
		 <%= f.select :academicyear, [["11-12", "11-12"], ["12-13", "12-13"], ["13-14", "13-14"],["14-15", "14-15"], ["15-16", "15-16"]] %>
	</p>
	<!--Убрал время обучения -->
	<p>
		Воинское звание:<br />
		 <%= f.select :rank_id, options_for_select(@ranks.map{ |f| [f.name, f.id] })%>
	</p>
	<p>
		Состав:<br />
		 <%= f.select :consist_id, options_for_select(@consists.map{ |f| [f.name, f.id] })%>
	</p>
	<p>
		Военкомат:<br />
		 <%= f.select :recruitmentoffice_id, options_for_select(@recruitmentoffices.map{ |f| [f.smallname, f.id] })%>
	</p>
	<p>
		Должность:<br />
		 <%= f.select :position_id, options_for_select(@positions.map{ |f| [f.name, f.id] })%>
	</p>
	<p>
		<%= f.input :specialaccount, as: :boolean, checked_value: ["Cу"], unchecked_value: nil, collection: [ "Cу" ], :label => 'Спецучет:' %>
	
		 <%= f.input :mobileorder, as: :boolean, checked_value: ["Моб."], unchecked_value: nil, collection: [ "Моб." ], :label => 'Мобпредписание:' %>

		 Категории:<br />
		 <%= f.select :category, [[" ", " "], ["Ра", "Ра"], ["О", "О"], ["Во", "Во"], ["Ру", "Ру"], ["Дс", "Дс"]] %>
	</p>
	<p> 
		<%= f.input :note, :label => 'Примечание(№ телефона):' %>
	</p>


	<%= f.submit "Сохранить", :class => "btn btn-success" %>
<% end -%>
<hr>

app/views/personalfiles/edit.html.erb
<%= render "form" %>

app/views/personalfiles/index.html.erb
<p>
<%= link_to "Создать призывника", new_personalfile_path, :class => "btn" %>
<!--<%= link_to "Полный список", more_personalfiles_path, :class => "btn" %>-->
</p>
<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">I. Общие сведения</a></li>
    <li><a href="#tab2" data-toggle="tab">II. Сведения о воинском учете</a></li>
    <li><a href="#tab3" data-toggle="tab">III. Назначения и перемещения</a></li>
    <li><a href="#tab4" data-toggle="tab">IV. Отпуска</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
		<table class="table table-striped table-bordered" >
			<thead>
					<tr>
						<th><%= sort_link @search, :id, "№" %></th>
						<th><%= sort_link @search, :firstname, "ФИО" %></th>
						<th><%= sort_link @search, :gender, "Пол" %></th>
						<th><%= sort_link @search, :date_of_birth, "Год" %></th>
						<th><%= sort_link @search, :place_of_birth, "Место рождения" %></th>
						<th><%= sort_link @search, :education, "Образование" %></th>
						<th><%= sort_link @search, :family_status, "Семейное положение" %></th>
						<th><%= sort_link @search, :family, "Состав семьи" %></th>
						<th>№ Спец</th>
						<th><%= sort_link @search, :specialty_id, "Наз.Спец" %></th>
						<th>Наз.Фак</th>
						<!--<th><%= sort_link @search, :traningcourse, "Курс" %></th>
						<th><%= sort_link @search, :academicyear, "Уч.год" %></th>
						<th><%= sort_link @search, :traning_period, "Срок обуч." %></th>
						<th><%= sort_link @search, :position_id, "Должность" %></th>
						<th><%= sort_link @search, :rank_id, "Звание" %></th>
						<th><%= sort_link @search, :consist_id, "Состав" %></th>
						<th><%= sort_link @search, :recruitmentoffice_id, "Военкомат" %></th>
						<th>Сп.Уч</th>
						<th>Мб.Пр.</th>
						<th>Кат.</th>-->
						<th>Примечание</th>
					</tr>
			</thead>
			<tbody>		
			<% if !@personalfiles.blank? %>
			<% @personalfiles.each do |personalfile| %>
			    <tr>
			    	<td>
			    		<%= personalfile.id %>
			    	</td>
			    	<td>
			    		<%= personalfile.firstname %><br />
			    	
			  			<%= personalfile.middlename %><br />

			  			<%= personalfile.lastname %>
			  		</td>
			  		<td>
			  			<%= personalfile.gender %>
			  		</td>
			  		<td>
			  			<%= personalfile.date_of_birth %>
			  		</td>
			  		<td>
			  			<%= personalfile.place_of_birth %>
			  		</td>
			  		<td>
			  			<%= personalfile.education %>
			  		</td>
			  		<td>
			  			<%= personalfile.family_status %>
			  		</td>
			  		<td>
			  			<%= personalfile.family %>
			  		</td>
			  		<td>
			  			<%= personalfile.specialty.try(:specialtynumber) %>
			  		</td>
			  		<td>
			  			<%= personalfile.specialty.try(:specialtyname) %>
			  		</td>	
			  		<td>
			  			<%= personalfile.specialty.try(:faculty).try(:facultyname) %>	
			  		</td>
			  		<!--<td>
			  			<%= personalfile.traningcourse %>
			  		</td>
			  		<td>
			  			<%= personalfile.academicyear %>
			  		</td>
			  		<td>
			  			<%= personalfile.specialty.try(:training_term) %>
			  		</td>
			  		<td>
			  			<%= personalfile.position.try(:name) %>
			  		</td>
			  		<td>
			  			<%= personalfile.rank.try(:name) %>
			  		</td>
			  		<td>
			  			<%= personalfile.consist.try(:name) %>
			  		</td>
			  		<td>
			  			<%= personalfile.recruitmentoffice.try(:smallname) %>
			  		</td>
			  		<td>
			  			<%= personalfile.specialaccount %>
			  		</td>
			  		<td>
			  			<%= personalfile.mobileorder %>
			  		</td>
			  		<td>
			  			<%= personalfile.category %>
			  		</td>-->
			  		<td>
			  			<%= personalfile.note %>
			  		</td>
			  		<td>
			  			<%= link_to '', personalfile_path(personalfile), :class => "icon-print" %>
			  		</td>	
			  		<td>
			  			<%= link_to 'Изменить', edit_personalfile_path(personalfile), :class => 'btn btn-mini' %>
			  		</td>
			  		<td>
			  			<%= link_to 'Удалить', personalfile, method: :delete, :class => 'btn btn-mini btn-danger' %>
			  		</td>
			    </tr>
			<% end %>
			<% else %>
			  
			<% end %>
			</tbody>
		</table>
</div>
    <div class="tab-pane" id="tab2">
      <table class="table table-striped table-bordered" >
			<thead>
					<tr>
						<th><%= sort_link @search, :firstname, "ФИО" %></th>
						<th><%= sort_link @search, :position_id, "Должность" %></th>
						<th><%= sort_link @search, :rank_id, "Звание" %></th>
						<th><%= sort_link @search, :consist_id, "Состав" %></th>
						<th><%= sort_link @search, :recruitmentoffice_id, "Военкомат" %></th>
						<th>Сп.Уч</th>
						<th>Мб.Пр.</th>
						<th>Кат.</th>
					</tr>
			</thead>
			<tbody>		
			<% if !@personalfiles.blank? %>
			<% @personalfiles.each do |personalfile| %>
			    <tr>
			    	<td>
			    		<%= personalfile.firstname %><br />
			    	
			  			<%= personalfile.middlename %><br />

			  			<%= personalfile.lastname %>
			  		</td>
			    	<td>
			  			<%= personalfile.position.try(:name) %>
			  		</td>
			  		<td>
			  			<%= personalfile.rank.try(:name) %>
			  		</td>
			  		<td>
			  			<%= personalfile.consist.try(:name) %>
			  		</td>
			  		<td>
			  			<%= personalfile.recruitmentoffice.try(:bigname) %>
			  		</td>
			  		<td>
			  			<%= personalfile.specialaccount %>
			  		</td>
			  		<td>
			  			<%= personalfile.mobileorder %>
			  		</td>
			  		<td>
			  			<%= personalfile.category %>
			  		</td>
			  		<td>
			  			<%= link_to '', personalfile_path(personalfile), :class => "icon-print" %>
			  		</td>	
			  		<td>
			  			<%= link_to 'Изменить', edit_personalfile_path(personalfile), :class => 'btn btn-mini' %>
			  		</td>
			  		<td>
			  			<%= link_to 'Удалить', personalfile, method: :delete, :class => 'btn btn-mini btn-danger' %>
			  		</td>
			    </tr>
			<% end %>
			<% else %>
			  
			<% end %>
			</tbody>
		</table>
		</div>
		<div class="tab-pane" id="tab3">
      		<p>ПУСТО!</p>
    	</div>
    	<div class="tab-pane" id="tab4">
      		<p>ПУСТО!</p>
    	</div>
	  </div>
	</div>	

app/views/personalfiles/more.html.erb
<table class="table table-striped table-bordered" >
			<thead>
				<!--<%= search_form_for @search do |f| %>
				<%= f.submit %>	
				<%= f.search_field :id_cont %>
				<% end %>-->
						<th></th>
						<th>Изображение</th>
						<th><%= sort_link @search, :id, "№" %></th>
						<th><%= sort_link @search, :firstname, "ФИО" %></th>
						<!--<th><%= sort_link @search, :gender, "Пол" %></th>-->
						<th><%= sort_link @search, :date_of_birth, "Год" %></th>
						<!--<th><%= sort_link @search, :place_of_birth, "Место рождения" %></th>
						<th><%= sort_link @search, :education, "Образование" %></th>
						<th><%= sort_link @search, :family_status, "Семейное положение" %></th>
						<th><%= sort_link @search, :family, "Состав семьи" %></th>-->
						<th>№ Спец</th>
						<th><%= sort_link @search, :specialty_id, "Наз.Спец" %></th>
						<th>Наз.Фак</th>
						<th><%= sort_link @search, :traningcourse, "Курс" %></th>
						<th><%= sort_link @search, :academicyear, "Уч.год" %></th>
						<th><%= sort_link @search, :training_term, "Срок обуч." %></th>
						<th><%= sort_link @search, :position_id, "Должность" %></th>
						<th><%= sort_link @search, :rank_id, "Звание" %></th>
						<th><%= sort_link @search, :consist_id, "Состав" %></th>
						<th><%= sort_link @search, :recruitmentoffice_id, "Военкомат" %></th>
						<th>Сп.Уч</th>
						<th>Мб.Пр.</th>
						<th>Кат.</th>
						<th>Примечание</th>
					</tr>
			</thead>
			<%= form_tag destroy_multiple_personalfiles_path, method: :delete do %>
			<tbody>		
			<% if !@personalfiles.blank? %>
			<% @personalfiles.each do |personalfile| %>
			    <tr>
			    	<td>
			    		<%= check_box_tag "personalfiles[]", personalfile.id %>
			    	</td>
			    	<td>
			    		<%= image_tag(personalfile.image_url, class: "icon") %>
			    	</td>
			    	<td>
			    		<%= personalfile.id %>
			    	</td>
			    	<td>
			    		<%= personalfile.firstname %><br />
			    	
			  			<%= personalfile.middlename %><br />

			  			<%= personalfile.lastname %>
			  		</td>
			  		<!--<td>
			  			<%= personalfile.gender %>
			  		</td>-->
			  		<td>
			  			<%= personalfile.date_of_birth %>
			  		</td>
			  		<!--<td>
			  			<%= personalfile.place_of_birth %>
			  		</td>
			  		<td>
			  			<%= personalfile.education %>
			  		</td>
			  		<td>
			  			<%= personalfile.family_status %>
			  		</td>
			  		<td>
			  			<%= personalfile.family %>
			  		</td>-->
			  		<td>
			  			<%= personalfile.specialty.try(:specialtynumber) %>
			  		</td>
			  		<td>
			  			<%= personalfile.specialty.try(:specialtyname) %>
			  		</td>	
			  		<td>
			  			<%= personalfile.specialty.try(:faculty).try(:facultyname) %>	
			  		</td>
			  		<td>
			  			<%= personalfile.traningcourse %>
			  		</td>
			  		<td>
			  			<%= personalfile.academicyear %>
			  		</td>
			  		<td>
			  			<%= personalfile.specialty.try(:training_term) %>
			  		</td>
			  		<td>
			  			<%= personalfile.position.try(:name) %>
			  		</td>
			  		<td>
			  			<%= personalfile.rank.try(:name) %>
			  		</td>
			  		<td>
			  			<%= personalfile.consist.try(:name) %>
			  		</td>
			  		<td>
			  			<%= personalfile.recruitmentoffice.try(:smallname) %>
			  		</td>
			  		<td>
			  			<%= personalfile.specialaccount %>
			  		</td>
			  		<td>
			  			<%= personalfile.mobileorder %>
			  		</td>
			  		<td>
			  			<%= personalfile.category %>
			  		</td>
			  		<td>
			  			<%= personalfile.note %>
			  		</td>
			  		<td>
			  			<%= link_to '', personalfile_path(personalfile), :class => "icon-print" %>
			  		</td>	
			  		<td>
			  			<%= link_to 'Изменить', edit_personalfile_path(personalfile), :class => 'btn btn-mini' %>
			  		</td>
			  		<td>
			  			<%= link_to 'Удалить', personalfile, method: :delete, :class => 'btn btn-mini btn-danger' %>
			  		</td>
			    </tr>
			<% end %>
			<% else %>
			  
			<% end %>
			</tbody>
		</table>
		<%= submit_tag "Удалить все", :class => 'btn btn-danger' %>
		<% end %>

app/views/personalfiles/new.html.erb
<%= render 'form' %>

app/views/personalfiles/show.html.erb
<div>
<a class= "btn btn-primary" onClick="javascript:CallPrint('print-content');" title="Распечатать проект">Распечатать</a>
</div>
<div float = 'right' class = 'container' id="print-content" >
		<div class = 'top'>
			<div class = 'left'>
				<table>
					<tr><th>Минестерство образования и науки</th></tr>
					<tr><th>Российской федирации</th></tr>
					<tr><td>Федеральное государственное бюджетное</td></tr>
					<tr><td>образовательное учереждение высшего</td></tr>
					<tr><td>профессионального оброзования</td></tr>
					<tr><th>"Тверской государственный университет"</th></tr>
					<tr><th>(ТвГУ)</th></tr>
					<tr><td>Желябова ул., д.33 Тверь. 170100</td></tr>
					<tr><td>Телефоны 34-24-52, 63-02-34</td></tr>
					<tr><td>___________№____________</td></tr>
				</table>
			</div>
			<div class = 'right' , float = 'left'>
				<table>
					<tr><td>Приложение №2</td></tr>
					<tr><td>к Перечню(п..3)</td></tr>
					<tr><td>к Приложению №32</td></tr>
					<tr><td>к Инструкции</td></tr>
					<tr><td>утв. приказом Минобороны РФ</td></tr>
					<tr><td>от 2 октября 2007 г. №400</td></tr>
				</table>

			</div> 
		</div>
		<div class = 'content'>
			<h1 align = 'center' >Справка</h1>
			<p align = 'center'> 
				Выдана гражданину <strong><%= @per.firstname %> <%= @per.middlename %> <%= @per.lastname %></strong><br/>
				<strong><%= @per.year %></strong> года рождения, в том что он в _____________поступил имея <br>
				образование __________________ в Тверской государственный университет,<br>
				приказ № _________________ от __________________г. и в настоящее время<br>
				обучаеться на <strong><%= @per.traningcourse %></strong> курсе по очной форме обучения по напровлению<br>
				подготовки(специальности) <strong><%= @per.specialty.try(:specialtyname) %> <%= @per.specialty.try(:specialtynumber) %> <%= @per.specialty.try(:faculty).try(:facultyname) %></strong> <br>
				имеющие государственную акредитацию серия 90А01 № 0000430, гестрицион-<br>
				ный № 0426 от 15.03.2013 года (срок действия до 29.12.2018) и лецензию<br>
				напрово ведения образовательной деятельности серия ААА № 002243, регистра-<br>
				ционный № 0426 от 15.03.2013 года (срок дйствия-бессроно). Свидетельство об<br>
				аккредитации и лицензия выданы Федеральной службой по надзору в сфере обра-<br>
				зования и науки.<br>
			</p>
			<p align = 'center'>
				Окончание обучения в образовательном учереждении (окончание обучения<br>
				по программам послевузовского образования и защиты квалификационной работы)<br>
				<br>
				"_____" ________________  20___ г.<br>
				<br>
				Справка дана для предъявления в отдел военного комиссариата<br>
				___________________________________________________________<br>
				
				Ректор ______________________ А.В.Белоцерковский<br>
				Заключил контракт и приступил к обучеию по программе подготовки<br>
				офицера запаса с 20__г. Оканчание обучения "___" ____________  20__ г.<br>
				Аттестационный материал оформляет _________________________________<br>
				М.П. Начальник (заместитль начальника) военной кафедры<br>
				      (учебного военного центра)______________________________<br>
			</p>
		</div>
	</div>