config/routes.rb
SFAppSpANDFac::Application.routes.draw do
  devise_for :users

  resources :faculties
  resources :specialties
  resources :recruitmentoffices
  resources :ranks
  resources :consists
  resources :positions
  resources :personalfiles do
    get "more", on: :collection
    
    collection do
      delete 'destroy_multiple'
    end 
  end

  root to: "personalfiles#index"
  

end

app/models/consist.rb
class Consist < ActiveRecord::Base
	has_many :personalfiles
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
	has_many :specialties
end

app/models/personalfile.rb
class Personalfile < ActiveRecord::Base
	
	belongs_to :rank
	belongs_to :specialty
	belongs_to :consist
	belongs_to :recruitmentoffice
	belongs_to :position

	validates :firstname, presence: true
	validates :middlename, presence: true
	validates :lastname, presence: true
end

app/models/position.rb
class Position < ActiveRecord::Base
	has_many :personalfiles
end

app/models/rank.rb
class Rank < ActiveRecord::Base
	has_many :personalfiles
end

app/models/recruitmentoffice.rb
class Recruitmentoffice < ActiveRecord::Base
	has_many :personalfiles
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
	belongs_to :faculty
	has_many :personalfiles
end
            

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/consists_controller.rb
class ConsistsController < ApplicationController

	before_filter :find_consist, only: [:show, :edit, :update, :destroy]

	def new
		@con = Consist.new
	end

	def create
		@con = Consist.new consist_params
		@con.save
		redirect_to new_consist_path
	end
	
	def show
	end

	def index
		@consists = Consist.all
	end

	def edit
	end
	
	def update
		@con.update_attributes(consist_params)
		redirect_to consists_path
	end

	def destroy
		@con.destroy
		redirect_to consists_path
	end
		
	private 

	def find_consist
		@con = Consist.find(params[:id])
	end

	def consist_params
		params[:consist].permit(:name)
	end
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController

	before_filter :find_faculty, only: [:show, :edit, :update, :destroy]

	def new
		@fac = Faculty.new
	end

	def create
		@fac = Faculty.new faculty_params
		@fac.save
		redirect_to new_faculty_path
	end
	
	def show
	end

	def index
		@faculties = Faculty.all
	end

	def edit
	end
	
	def update
		@fac.update_attributes(faculty_params)
		redirect_to faculties_path
	end

	def destroy
		@fac.destroy
		redirect_to faculties_path
	end
		
	private 

	def find_faculty
		@fac = Faculty.find(params[:id])
	end

	def faculty_params
		params[:faculty].permit(:facultyname)
	end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
	def new
		@pos = Position.new
	end

	def create
		@pos = Position.new position_params
		@pos.save
		redirect_to new_position_path
	end
	def show
		@pos = Position.find(params[:id])
	end
	def index
		@positions = Position.all
	end

	def edit
		@pos = Position.find(params[:id])
	end
	
	def update
		@pos = Position.find(params[:id])
		@pos.update_attributes(position_params)
		redirect_to positions_path
	end

	def destroy
		@pos = Position.find(params[:id])
		@pos.destroy
		redirect_to positions_path
	end
		
	private 

	def position_params
		params[:position].permit(:name)
	end
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
	def new
		@ran = Rank.new
	end

	def create
		@ran = Rank.new rank_params
		@ran.save
		redirect_to new_rank_path
	end
	def show
		@ran = Rank.find(params[:id])
	end
	def index
		@ranks = Rank.all
	end

	def edit
		@ran = Rank.find(params[:id])
	end
	
	def update
		@ran = Rank.find(params[:id])
		@ran.update_attributes(rank_params)
		redirect_to ranks_path
	end

	def destroy
		@ran = Rank.find(params[:id])
		@ran.destroy
		redirect_to ranks_path
	end
		
	private 

	def rank_params
		params[:rank].permit(:name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consists_helper.rb
module ConsistsHelper
end

app/helpers/facultis_helper.rb
module FacultisHelper
end

app/helpers/personalfiles_helper.rb
module PersonalfilesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/helpers/specialties_helper.rb
module SpecialtiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SFAppSpANDFac</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script language="javascript">
	function CallPrint(strid)
	{
	 var prtContent = document.getElementById(strid);
	 var prtCSS = '<link rel="stylesheet" href="spravka.css" >';
	 var WinPrint = window.open('','','left=50,top=50,width=800,height=640,toolbar=0,scrollbars=1,status=0');
	 WinPrint.document.write('<div id="print" class="contentpane">');
	 WinPrint.document.write(prtCSS);
	 WinPrint.document.write(prtContent.innerHTML);
	 WinPrint.document.write('</div>');
	 WinPrint.document.close();
	 WinPrint.focus();
	 WinPrint.print();
	 WinPrint.close();
	 prtContent.innerHTML=strOldOne;
	}
  </script>
</head>
<body>
	<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
    
      <% if user_signed_in? %>

      <a class="brand" ><%= image_tag("tvgu_0.jpg", size: "20") %>  <%= current_user.email %></a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Личные карточки", personalfiles_path %></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Справочники<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Факультеты", faculties_path %></li>
            <li><%= link_to "Специальности", specialties_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Звания", ranks_path %></li>
            <li><%= link_to "Составы", consists_path %></li>
            <li><%= link_to "Комиссариаты", recruitmentoffices_path %></li>
            <li><%= link_to "Должности", positions_path %></li>
          </ul>
        </li>
          <li><%= link_to "Общий список", more_personalfiles_path  %></li>
          <form class="navbar-search pull-left">
            <input type="text" class="search-query" placeholder="Поиск">
          </form>
          <li><%= link_to "Выйти", destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <!--<%= link_to "Войти", new_user_session_path %>-->
          <% end -%>
        </ul>
      </div>
    </div>
  </div>
</div>
<!--<% if user_signed_in? %>	
	<%= current_user.email %> <%= link_to "Выйти", destroy_user_session_path, :method => :delete %>
<% else %>
 <%= link_to "Регистироваться", new_user_registration_path %> или  <%= link_to "Войти", new_user_session_path %>
<% end %> -->
<%= yield %>

</body>
</html>